version: "3.7"

services:
  rabbit:
    image: rabbitmq:3.8.0-management-alpine
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
  consumer:
    build: ./output
    # image: consumer:v1
    container_name: consumer
    restart: always
    depends_on:
      - rabbit
