version: '3.4'

services:
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3.8.0-management-alpine
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  producer:
    image: ${DOCKER_REGISTRY-}producer
    build:
      context: .
      dockerfile: Producer/Dockerfile
    depends_on:
      - rabbit

